Remove-Item -Force -Recurse -Path '.\.vs'
Remove-Item -Force -Recurse -Path '.\Apex Legends\bin'
Remove-Item -Force -Recurse -Path '.\Apex Legends\obj'
Remove-Item -Force -Recurse -Path '.\Apex Legends\r2'
Remove-Item -Force -Recurse -Path '.\Apex Legends\*.ini'
Remove-Item -Force -Recurse -Path '.\Apex Legends\*.vcxproj.user'
Remove-Item -Force -Recurse -Path '.\release'
